# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
before_script:
    - brew update
    - brew unlink xctool
    - brew install xctool
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script: pod lib lint
